### ISSUE TITLE
bug: menuBar 样式自定义需要优化

### ISSUE THREAD

**Issue by mortalYoung** [DTStack/molecule#623]
### Describe the bug

我想要自定义 menuBar 的样式，但是目前优化有以下一些问题
1. 自定义高度和背景颜色的时候，需要写的代码较多
```css
// expected
.mo-menuBar--horizontal {
	height: $menuBar-size;
	background: var(--editorIndentGuide-activeBackground);
}

// 需要修改如下：
.mo-menuBar--horizontal {
	height: $menuBar-size;
	background: var(--editorIndentGuide-activeBackground);

	> .mo-menu {
		height: $menuBar-size;
		background: var(--editorIndentGuide-background);
	}
}
```
2. hover 的颜色有问题：
![test](https://user-images.githubusercontent.com/18719701/149700213-f262a5ba-66e1-46fa-a0f2-5bd0598e5d57.gif)

-   OS: MacOS
-   Browser: Chrome
-   Molecule: @dtinsight/molecule@0.9.0-beta.2
